#!/bin/sh -e
# Copyright (C) 2022 Fabian Mastenbroek.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

case "$1" in
    purge)
        rm -rf /var/cache/udm-iptv
        rm -rf "${UDM_IPTV_STATE_DIR:-/data/udm-iptv}"
        if [ -e /usr/share/debconf/confmodule ]
        then
                # Source debconf library and purge db
                # shellcheck source=/dev/null
                . /usr/share/debconf/confmodule
                db_purge
        fi
        ;;

    remove)
        # Leaving this enabled would reinstall the package on the next boot.
        if [ -d /run/systemd/system ]; then
            systemctl disable udm-iptv-restore.service > /dev/null 2>&1 || true
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0