name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: { contents: write, id-token: write, attestations: write, artifact-metadata: write }
    steps:
      - name: Checkout Sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with: { fetch-depth: 0 }
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with: { go-version-file: go.mod, cache-dependency-path: go.sum }
      - name: Test Go
        run: go test ./...
      - name: Check Go vulnerabilities
        run: go tool govulncheck ./...
      - name: Create Draft Release and Upload Assets
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env: { GITHUB_TOKEN: "${{ github.token }}" }
      - name: Attest Packages
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-path: |
            dist/**/udm-iptv
            dist/*.deb
            dist/SHA256SUMS
      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: build-artifacts
          if-no-files-found: error
          path: |
            dist/**/udm-iptv
            dist/*.deb
            dist/SHA256SUMS
      - name: Publish Release
        env: { GH_TOKEN: "${{ github.token }}" }
        run: gh release edit "${GITHUB_REF#"refs/tags/"}" --draft=false
